# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff72d6104eb1d114e30b16f4de5eeca3"
name = "wishlist"
handle = "wishlist-454"
application_url = "https://specifications-displayed-served-substance.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-b4809b87.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://specifications-displayed-served-substance.trycloudflare.com/auth/callback",
  "https://specifications-displayed-served-substance.trycloudflare.com/auth/shopify/callback",
  "https://specifications-displayed-served-substance.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
